site_name: 'ConnecME'
site_description: 'ConnectME docs'
site_author: 'gfursin@gmail.com'
docs_dir: 'docs/'

nav:
  - Home: index.md

theme:
  name: 'material'

theme:
  name: material
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Circular'
    code: 'Inconsolata'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: True
